hibench.default.map.parallelism 2
hibench.default.shuffle.parallelism 2
hibench.hadoop.configure.dir /home/sparker/hadoop-3.3.6/etc/hadoop
hibench.hadoop.executable /home/sparker/hadoop-3.3.6/bin/hadoop
hibench.hadoop.home /home/sparker/hadoop-3.3.6
hibench.hdfs.data.dir hdfs://spark-cluster-master:9000/HiBench-Control/datasets/bcdaeb306b8f3e90aa82e67b-c3fa615d
hibench.hdfs.master hdfs://spark-cluster-master:9000
hibench.masters.hostnames spark-cluster-master
hibench.report.dir /home/sparker/HiBench/report/control/1da6421b-e30c-499d-aa6f-3a0928e3c7af/ml.linear/1
hibench.report.name hibench.csv
hibench.scale.profile tiny
hibench.slaves.hostnames spark-cluster-slave-1 spark-cluster-slave-2 spark-cluster-slave-3
hibench.spark.home /usr/local/spark
hibench.spark.master yarn
hibench.workload.output hdfs://spark-cluster-master:9000/HiBench-Control/runs/1da6421b-e30c-499d-aa6f-3a0928e3c7af/ml.linear/1
hibench.yarn.deploy.mode client
hibench.yarn.executor.cores 1
hibench.yarn.executor.num 1
mapreduce.map.memory.mb 1024
mapreduce.reduce.memory.mb 1024
spark.app.benchmark.group.id 1da6421b-e30c-499d-aa6f-3a0928e3c7af
spark.default.parallelism 2
spark.driver.memory 2g
spark.dynamicAllocation.enabled false
spark.eventLog.dir hdfs://spark-cluster-master:9000/shared/spark-logs
spark.executor.cores 1
spark.executor.instances 1
spark.executor.memory 2g
spark.extraListeners org.hibench.sparkbench.common.BenchmarkListener
spark.sql.adaptive.enabled false
spark.sql.shuffle.partitions 2
spark.yarn.historyServer.address spark-cluster-master:18080
spark.yarn.submit.waitAppCompletion true
spark.yarn.tags hibench-1da6421b-e30c-499d-aa6f-3a0928e3c7af
