s#sleep
hibench.sleep.tiny.mapper.seconds 	    3
hibench.sleep.small.mapper.seconds 	    30
hibench.sleep.large.mapper.seconds 	    90
hibench.sleep.huge.mapper.seconds 	    90
hibench.sleep.gigantic.mapper.seconds 	90
hibench.sleep.bigdata.mapper.seconds 	  10

hibench.sleep.mapper.seconds		  ${hibench.sleep.${hibench.scale.profile}.mapper.seconds}

# export for shell script
hibench.workload.input			dummy
hibench.workload.output			dummy
