# Hadoop Home (HDInsight uses current client symlink)
#hibench.hadoop.home     /usr/hdp/current/hadoop-client

# Hadoop home docker
hibench.hadoop.home     /home/sparker/hadoop-3.3.6

# Path to hadoop executable
hibench.hadoop.executable     ${hibench.hadoop.home}/bin/hadoop

# Hadoop configuration directory
#hibench.hadoop.configure.dir  /etc/hadoop/conf
# Hadoop configuration directory Docker
hibench.hadoop.configure.dir  ${hibench.hadoop.home}/etc/hadoop

# Root HDFS path
#hibench.hdfs.master           hdfs://mycluster
# The root HDFS path to store HiBench data
### Modified: original: hdfs://localhost:8020 *** hadoop/etc/hadoop/core-site.xml --> <value>hdfs://spark-cluster-master:9000</value>
hibench.hdfs.master       hdfs://spark-cluster-master:9000

# Hadoop release
hibench.hadoop.release        apache
